/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/index` | `/profile/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/createlisting` | `/profile/createlisting`; params?: Router.UnknownInputParams; } | { pathname: `/../components/UI/Dropdown`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LabeledPriceInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LabeledTextArea`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/mylistings` | `/profile/mylistings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/product/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/index` | `/profile/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/createlisting` | `/profile/createlisting`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/UI/Dropdown`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/LabeledPriceInput`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/LabeledTextArea`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/mylistings` | `/profile/mylistings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/product/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/index${`?${string}` | `#${string}` | ''}` | `/profile/index${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/settings${`?${string}` | `#${string}` | ''}` | `/profile/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/createlisting${`?${string}` | `#${string}` | ''}` | `/profile/createlisting${`?${string}` | `#${string}` | ''}` | `/../components/UI/Dropdown${`?${string}` | `#${string}` | ''}` | `/../components/LabeledPriceInput${`?${string}` | `#${string}` | ''}` | `/../components/LabeledTextArea${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/mylistings${`?${string}` | `#${string}` | ''}` | `/profile/mylistings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signin${`?${string}` | `#${string}` | ''}` | `/signin${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/favorites${`?${string}` | `#${string}` | ''}` | `/favorites${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/index` | `/profile/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/createlisting` | `/profile/createlisting`; params?: Router.UnknownInputParams; } | { pathname: `/../components/UI/Dropdown`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LabeledPriceInput`; params?: Router.UnknownInputParams; } | { pathname: `/../components/LabeledTextArea`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/mylistings` | `/profile/mylistings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signin` | `/signin`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/favorites` | `/favorites`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | `/product/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/product/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
